name: ecommerce_web
description: "Website UI for ecommerce system."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.5
  go_router: ^14.1.4
  dio: ^5.4.3+1
  equatable: ^2.0.5
  get_it: ^7.7.0
  shimmer: ^3.0.0
  collection: ^1.18.0
  flutter_svg: ^2.0.10+1
  file_picker: ^8.0.0+1
  intl: ^0.19.0
  uuid: ^4.4.2
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true